###
### Rule modifications 
###

line_length:
    warning: 200
    error: 500
    ignores_function_declarations: true
    ignores_comments: false
    ignores_urls: true

file_length:
    warning: 1000
    error: 2000
    ignore_comment_only_lines: true

